# -*- coding: utf-8 -*-
"""HN 댓글에서 'AI 티' 지적을 센다. 지표 = 주제 관련 댓글 중 그 항목을 언급한 비율."""
import json, re, html, collections, pathlib

raw = json.loads(pathlib.Path("hn_corpus.json").read_text(encoding="utf-8"))

def clean(h):
    t = h.get("comment_text") or ""
    t = re.sub(r"<[^>]+>", " ", html.unescape(t))
    return re.sub(r"\s+", " ", t)

DESIGN = re.compile(r"\b(design(ed|er|s)?|ui|ux|website|web ?site|landing page|homepage|"
                    r"front[- ]?end|css|layout|typography|font|color|palette|theme)\b", re.I)
AIGEN  = re.compile(r"\b(ai[- ]generated|ai generated|generated by (ai|an? llm)|llm|chatgpt|claude|"
                    r"cursor|copilot|vibe[- ]cod|ai slop|slop|looks like ai|smells like ai|"
                    r"ai[- ]made|genai|gpt)\b", re.I)

TELLS = {
    "보라·인디고 강조색":        r"\b(purple|violet|indigo)\b",
    "그라디언트(특히 글자)":      r"\bgradient",
    "shadcn·Tailwind 기본값":    r"\b(shadcn|tailwind)\b",
    "전부 둥근 모서리·알약":      r"\b(rounded[- ](corner|everything|lg|xl|2xl)|border-radius|pill[- ]shaped)\b",
    "다 똑같이 생겼다":           r"\b(all look the same|same look|look(s)? identical|cookie[- ]cutter|homogen|samey|indistinguishable)\b",
    "히어로+3카드 골격":          r"\b(hero section|three (feature )?cards|3[- ]column|feature cards|above the fold)\b",
    "과한 애니메이션·스크롤":     r"\b(fade[- ]in|scroll[- ]animat|animation(s)?|parallax|framer[- ]motion)\b",
    "이모지를 아이콘으로":        r"(\bemoji\b|[\U0001F300-\U0001FAFF])",
    "기본 폰트(Inter 등)":        r"\b(inter|geist|roboto|helvetica|system font|default font)\b",
    "크림+세리프+세이지(2026)":   r"\b(cream|beige|off[- ]white background|instrument serif|fraunces|playfair|sage green)\b",
    "글로우·네온":               r"\b(glow(ing)?|neon)\b",
    "다크모드":                  r"\bdark mode\b",
    "글래스모피즘":              r"\bglass(morphism)?\b",
    "벤토 그리드":               r"\bbento\b",
    "여백·가운데정렬 과다":       r"\b(whitespace|white space|centered everything|too much padding)\b",
    "카피 상투구":               r"\b(unleash|supercharge|transform your|effortlessly|reimagin|elevate your)\b",
    "간격·정렬이 제멋대로":       r"\b(inconsistent (spacing|padding)|misalign|off by a few pixels|no spacing system|arbitrary (padding|spacing))\b",
    "정보 위계가 없다":           r"\b(visual hierarchy|information hierarchy|no hierarchy|everything (is )?the same weight)\b",
    "스톡 일러스트":              r"\b(undraw|stock (photo|illustration)|clipart|generic illustration)\b",
}

on = []
for h in raw:
    t = clean(h)
    if len(t) < 40:
        continue
    if DESIGN.search(t) and AIGEN.search(t):
        on.append((h, t))

print(f"수집 댓글 {len(raw)}건 → 주제 관련 {len(on)}건")
yrs = collections.Counter(h["created_at"][:4] for h, _ in on)
print("연도별:", dict(sorted(yrs.items())))
print()
rows = []
for name, pat in TELLS.items():
    rx = re.compile(pat, re.I)
    n = sum(1 for _, t in on if rx.search(t))
    rows.append((n, n / len(on) * 100, name))
rows.sort(reverse=True)
print(f"{'항목':<28}{'건수':>6}{'비율':>9}")
for n, p, name in rows:
    print(f"{name:<28}{n:>6}{p:>8.1f}%")

json.dump([{"id": h["objectID"], "date": h["created_at"], "url": h.get("story_url"),
            "text": t} for h, t in on], open("hn_ontopic.json", "w", encoding="utf-8"),
          ensure_ascii=False)
